// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateCustomerInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Company     string `json:"company"`
}

type Customer struct {
	ID          string `json:"_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Company     string `json:"company"`
}

type DeleteCustomer struct {
	CustomerID string `json:"customerId"`
}

type UpdateCustomerInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Company     *string `json:"company,omitempty"`
}
